Repository karanaditya993/tidy-tab, pull requests merged in 2021-01, with the labels that each got.

#1 feat: POC for adding partitioned tab data
  popup.css
  popup.html
  popup.js
Labels: enhancement

#3 bug: Add location reload to remove callback
  popup.js
Labels: bug

#4 chore: Change list to show name instead of url
  popup.js
Labels: enhancement

#5 chore: Rename to TidyTab
  README.md
  manifest.json
Labels: enhancement

#8 feat: Add badges to UI
  popup.css
  popup.js
Labels: enhancement

#7 feat: Initial Design
  cleaning-sm.png
  cleaning.png
  header.png
  popup.css
  popup.html
  popup.js
Labels: enhancement

#9 feat: Add badge color based on tab number threshold
  popup.css
  popup.js
Labels: enhancement

#11 feat: Revised list view
  cleaning.png
  header.png
  manifest.json
  popup.css
  popup.html
  popup.js
  trash.png
Labels: enhancement

#10 feat: Grid system redesign and switch between list/grid views
  popup.css
  popup.html
  popup.js
Labels: enhancement

#12 chore: Refactor JS
  assets/images/trash.png
  cleaning-sm.png
  manifest.json
  popup.css
  popup.html
  popup.js
Labels: refactor

#14 feat: Add close button badge
  assets/images/chrome-logo.png
  popup.css
  popup.js
Labels: enhancement

#15 feat: Add dark mode
  popup.css
  popup.html
  popup.js
Labels: enhancement

#16 feat: MVP all set!
  popup.css
  popup.html
  popup.js
Labels: enhancement
